home:
    path: /
    controller: App\Controller\DefaultController::home

post_new:
    path: /nouvelle_annonce
    controller: App\Controller\DefaultController::newPost

annonce:
    path: /annonce/{alias}
    controller: App\Controller\DefaultController::annonce
